# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/c/Users/jerem/Desktop/CPP-BANK/projetcppbanque

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/c/Users/jerem/Desktop/CPP-BANK/projetcppbanque

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/jerem/Desktop/CPP-BANK/projetcppbanque/CMakeFiles /mnt/c/Users/jerem/Desktop/CPP-BANK/projetcppbanque//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/jerem/Desktop/CPP-BANK/projetcppbanque/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named projetcppbanque

# Build rule for target.
projetcppbanque: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 projetcppbanque
.PHONY : projetcppbanque

# fast build rule for target.
projetcppbanque/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/projetcppbanque.dir/build.make CMakeFiles/projetcppbanque.dir/build
.PHONY : projetcppbanque/fast

backOffice/backOffice.o: backOffice/backOffice.cpp.o
.PHONY : backOffice/backOffice.o

# target to build an object file
backOffice/backOffice.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/projetcppbanque.dir/build.make CMakeFiles/projetcppbanque.dir/backOffice/backOffice.cpp.o
.PHONY : backOffice/backOffice.cpp.o

backOffice/backOffice.i: backOffice/backOffice.cpp.i
.PHONY : backOffice/backOffice.i

# target to preprocess a source file
backOffice/backOffice.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/projetcppbanque.dir/build.make CMakeFiles/projetcppbanque.dir/backOffice/backOffice.cpp.i
.PHONY : backOffice/backOffice.cpp.i

backOffice/backOffice.s: backOffice/backOffice.cpp.s
.PHONY : backOffice/backOffice.s

# target to generate assembly for a file
backOffice/backOffice.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/projetcppbanque.dir/build.make CMakeFiles/projetcppbanque.dir/backOffice/backOffice.cpp.s
.PHONY : backOffice/backOffice.cpp.s

bankingApp/bankingApp.o: bankingApp/bankingApp.cpp.o
.PHONY : bankingApp/bankingApp.o

# target to build an object file
bankingApp/bankingApp.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/projetcppbanque.dir/build.make CMakeFiles/projetcppbanque.dir/bankingApp/bankingApp.cpp.o
.PHONY : bankingApp/bankingApp.cpp.o

bankingApp/bankingApp.i: bankingApp/bankingApp.cpp.i
.PHONY : bankingApp/bankingApp.i

# target to preprocess a source file
bankingApp/bankingApp.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/projetcppbanque.dir/build.make CMakeFiles/projetcppbanque.dir/bankingApp/bankingApp.cpp.i
.PHONY : bankingApp/bankingApp.cpp.i

bankingApp/bankingApp.s: bankingApp/bankingApp.cpp.s
.PHONY : bankingApp/bankingApp.s

# target to generate assembly for a file
bankingApp/bankingApp.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/projetcppbanque.dir/build.make CMakeFiles/projetcppbanque.dir/bankingApp/bankingApp.cpp.s
.PHONY : bankingApp/bankingApp.cpp.s

frontOffice/user.o: frontOffice/user.cpp.o
.PHONY : frontOffice/user.o

# target to build an object file
frontOffice/user.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/projetcppbanque.dir/build.make CMakeFiles/projetcppbanque.dir/frontOffice/user.cpp.o
.PHONY : frontOffice/user.cpp.o

frontOffice/user.i: frontOffice/user.cpp.i
.PHONY : frontOffice/user.i

# target to preprocess a source file
frontOffice/user.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/projetcppbanque.dir/build.make CMakeFiles/projetcppbanque.dir/frontOffice/user.cpp.i
.PHONY : frontOffice/user.cpp.i

frontOffice/user.s: frontOffice/user.cpp.s
.PHONY : frontOffice/user.s

# target to generate assembly for a file
frontOffice/user.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/projetcppbanque.dir/build.make CMakeFiles/projetcppbanque.dir/frontOffice/user.cpp.s
.PHONY : frontOffice/user.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/projetcppbanque.dir/build.make CMakeFiles/projetcppbanque.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/projetcppbanque.dir/build.make CMakeFiles/projetcppbanque.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/projetcppbanque.dir/build.make CMakeFiles/projetcppbanque.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... projetcppbanque"
	@echo "... backOffice/backOffice.o"
	@echo "... backOffice/backOffice.i"
	@echo "... backOffice/backOffice.s"
	@echo "... bankingApp/bankingApp.o"
	@echo "... bankingApp/bankingApp.i"
	@echo "... bankingApp/bankingApp.s"
	@echo "... frontOffice/user.o"
	@echo "... frontOffice/user.i"
	@echo "... frontOffice/user.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

